name: Flutter AAB Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni yuklash
      uses: actions/checkout@v4

    - name: Java-ni o'rnatish
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Flutter-ni o'rnatish
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.44.6'
        channel: 'stable'

    - name: Kutubxonalarni yuklash
      run: flutter pub get

    - name: AAB-ni yig'ish (Build App Bundle)
      run: flutter build appbundle --release

    - name: Tayyor AAB-ni yuklab olish uchun chiqarish
      uses: actions/upload-artifact@v4
      with:
        name: release-aab
        path: build/app/outputs/bundle/release/app-release.aab
